# Generated by Django 4.1 on 2022-08-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_DROGUERIA', '0002_clientes_tipo_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='tipo_Cliente',
            new_name='tipo_Proveedor',
        ),
    ]
