# Generated by Django 4.1 on 2022-08-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_DROGUERIA', '0003_rename_tipo_cliente_proveedores_tipo_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGENES_DIRECTORIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
            ],
        ),
    ]
