# Generated by Django 4.1 on 2022-08-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_DROGUERIA', '0004_imagenes_directorio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IMAGENES_DIRECTORIO',
            new_name='IMAGENES',
        ),
    ]
